### ISSUE TITLE
The table selector is truncated when in block quote

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-block-quote#28]
When table widget is inside blockquote the table's drag handler is truncated:

![selection_084](https://user-images.githubusercontent.com/247363/49385111-df29be80-f71c-11e8-98cf-0fba1bf9f038.png)

Blockquote has hidden overflow and table has not big enough padding:

```css
.ck-content blockquote {
    overflow: hidden;
}
```

**Comment by oleq** [comment]
I also think this is annoying. Let's see if we can do anything about that.

cc @dkonopka

**Comment by dkonopka** [comment]
It should be easy fix - just need to overwrite https://github.com/ckeditor/ckeditor5-table/blob/master/theme/table.css#L8 with:

```css
.ck-content blockquote > .table {
  margin-top: 2em;
}
```
